### ISSUE TITLE
The code generator has optimized the styling of [path] as it exceeds the max of 500KB.  

### ISSUE THREAD

**Issue by phanimandapati** [ramarao9/AttachmentUploader#11] opened 2020-08-18 12:26 UTC
Hi Rama, 

Can you please help us with resolving the issue [The code generator has optimized the styling of [path] as it exceeds the max of 500KB. ]. We are facing this for ReactDOM file. Since we need to customize as per our requirement. We can't use the existing solution file. Can you please help us resolving this issue, which will be of great help to us.
![Capture](https://user-images.githubusercontent.com/19855549/90512670-1c95e000-e17c-11ea-8db4-f0f96a7ac517.PNG)

**Comment by ramarao9** [comment] 2020-08-18 15:18
Hi Phani,

I will take a look and get back to you on this.

Could you provide me the steps to reproduce this or how you are customizing it on your end so I can mimic the behavior?

Thanks

**Comment by phanimandapati** [comment] 2020-08-18 15:40
Hi Ram,

Thanks for your reply. We are going to use different entity in place of
attachment entity. Once we drop the file it should create record of that
entity.
 So we were planning to use the existing source code instead of using
solution file. But when we tried to built existing source code we got the
below issue. We didn't make any changes, just straight away tried to build
it without changes in code.

Thanks & Regards
Phani

**Comment by ramarao9** [comment] 2020-08-19 03:07
@phanimandapati  Looks like this usually happens with Babel but it should not cause issues with generating the build. You can turn off the warning as described [here ](https://stackoverflow.com/questions/35192796/babel-note-the-code-generator-has-deoptimised-the-styling-of-app-js-as-it-exc/36880182)

Below is an example of how it generates the build outputs for me when I do `npm run build`
![image](https://user-images.githubusercontent.com/37280856/90585715-17945900-e19b-11ea-987d-36b36e13a951.png)


Did you also run the below commands after building the PCF component to generate the solution files?

Note: `msbuild /t:build /restore` is only needed for the first time to build the solution project by pulling down the NuGet dependencies as part of the restore. The second time and going forward you can just do `msbuild` to generate the solution files.

![image](https://user-images.githubusercontent.com/37280856/90586553-1532fe80-e19d-11ea-99ea-b240e60c8ff6.png)

When updating the versions for subsequent builds you would need to change it in the below places before creating a build and generating the solution files

- Navigate to /AttachmentUpload/ControlManifest.Input.xml and update the version on the control. This is an internal version used by the Power Platform to look for changes in the component.
- Navigate to /AttachmentDragandDrop/Other/Solution.xml and update the version.

**Comment by phanimandapati** [comment] 2020-08-19 03:10
Hi Ram,

Well I did try to use npm start to see UI part in wep page but I didn't see
anything, I will try to build solution and test it.

Thanks,
Phani

**Comment by ramarao9** [comment] 2020-08-19 03:14
So you do not see the below when doing `npm run start`? 

![image](https://user-images.githubusercontent.com/37280856/90587926-144f9c00-e1a0-11ea-8461-30e407948a8d.png)

Can you send me a screenshot of what happens after the message 'The code generator....'?

**Comment by phanimandapati** [comment] 2020-08-19 03:22
I did see it, but couldn't check the UI part in webpage. Well I tried
checking the compact part "pipe(babel({compact" and it's subsets but I
found nothing in the whole solution files. So i couldn't place the false
part. Well I think I better deploy control to D365 and check it directly.

I will be working on my actual requirements today. Very greatful for your
support. If I face further challenges I will try to contact you. Please
close the issue.

Thanks,
Phani

**Comment by ramarao9** [comment] 2020-08-19 03:36
I see, that makes sense now. Initially when the control is written there wasn't an easy way to test it in the UI other than tweaking the index.ts file and putting in fake data. So nothing renders locally until it has the necessary context it's looking for.

You could still do that by manipulating certain methods in the index file. Not sure if there have been any recent changes that would allow easier testing. Something I have on my list to look. 

No problem!

**Comment by phanimandapati** [comment] 2020-08-19 12:38
Hi Ram,

Small query requirement has to use custom entity in place of  attachment
entity is that scenario possible in pcf. Cause when we drop attachment into
pcf control, it should be added in same way how it's done with attachment
entity. I tried creating activity entity and made changes but count
replicate the same.

Kindly provide me your valuable suggestions. That would be of great help.

If possible can you share me your whatsapp number. For better
communication, if you don't mind.

Thanks & Regards
Phani

**Comment by ramarao9** [comment] 2020-08-23 01:16
So you created a custom activity entity and trying to use that to upload attachments? If that's the case the code currently only accepts email and appointment. Let me know and I can run some tests to see if it can be fixed to allow any activity entity including custom activity.

**Comment by phanimandapati** [comment] 2020-08-26 06:59
Hi Ram,

We need to add lookup and few fields to notes entity, but I think it's not
possible to add fields to notes entity right. Do you know anyways to do
that. If not we have to go with custom entity and make use of it to work
like notes entity.

Please let me know if you have any solution as such.

Thanks
Raju

**Comment by phanimandapati** [comment] 2020-08-26 13:45
Hi Rama,

I created a custom entity named fcpm_fileattachment(activity entity), I
have made the changes below in order to create a record in a custom entity.

[image: image.png]

But i am facing the below error, when i dropped the attachment.

[image: image.png]

Can you please help me resolve this issue?

Thanks,
raju

**Comment by phanimandapati** [comment] 2020-08-27 07:31
Got fixed

**Comment by ramarao9** [comment] 2020-08-28 16:46
@phanimandapati I did run a test on custom activity entity and was able to add attachments as expected. I was not able to see your screenshots above but glad you got it resolved. Closing the issue at this time.

**Closed as completed by ramarao9** 2020-08-28 16:46 UTC
